### PR TITLE
add-linters

### PR DESCRIPTION
**Pull request by prankulmahajan**

### CODE REVIEW

**Review by ambiknai — CHANGES_REQUESTED** [review]
Any way to fix the linter errors? I understand not all can be solved. But can we  still look at all suppressed ones and see if anything can be solved.

**Comment by prankulmahajan** [comment]
> Any way to fix the linter errors. I understand not all can be solved. But can we still look at all suppressed ones and see if anything can be solved.

@ambiknai Have fixed a few which were okay to do in my understanding. There are 4 instances where have still used `//nolint` and it is required to use them that way

**Review by ambiknai — APPROVED** [review]

**Review by arahamad — APPROVED** [review]
LGTM

**Comment by arahamad** [comment]
Can you please add your tests also before merging this PR

**Pull request merged**
